---
title: "jsmith_dataset_a"
author: "jsmith"
date: "November 4, 2017"
output: html_document
---

```{r setup, include=FALSE}
require(rpart)
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
hybridData <- read.csv('Data/a._2014_hybrid_phenotypic_data/g2f_2014_hybrid_raw.csv')
hybridData = subset(hybridData, hybridData$Plot.Discarded != "Yes" & hybridData$Filler != "Yes")

pedigree <- unique(hybridData$Pedigree, na.rm=TRUE)

labels <- c()
meanYields <- c()
medYields <- c()
occurrences <- c()
# par(mfrow=c(4,4))
for (i in seq(1:881)){
  selectedPedigree <- pedigree[i]
  dataset <- subset(hybridData, hybridData$Pedigree == selectedPedigree)
  currentMean <- mean(dataset$Grain.yield..bu.A., na.rm = TRUE)
  currentMed <- median(dataset$Grain.yield..bu.A., na.rm = TRUE)
  meanYields <- c(meanYields, currentMean)
  medYields <- c(medYields, currentMed)
  occurrences <- c(occurrences, sum(hybridData$Pedigree == selectedPedigree))
}

```

```{R}
max <- head(meanYields[order(-meanYields)])
min <- tail(meanYields[order(-meanYields)])
pop <- head(occurrences[order(-occurrences)])


cat("Best Pedigrees \n")
for (m in seq(1,5)){
  topPedigree <- pedigree[which(meanYields==max[m])]
  topSample <- occurrences[which(meanYields==max[m])]
  cat(sprintf("%d: %s Mean Yield: %f Sample Size: %d \n", m, topPedigree[1], max[m], topSample))
}

cat("\n Worst Pedigrees \n")
for (n in seq(1,5)){
  bottomPedigree <- pedigree[which(meanYields == min[n])]
  bottomSample <- occurrences[which(meanYields==min[n])]
  cat(sprintf("%d: %s Mean Yield: %f Sample Size: %d \n", 876+n, bottomPedigree[1], min[n], bottomSample))
}

cat("\n Most Popular Pedigrees \n")
for (p in seq(1,5)){
  bottomPedigree <- unique(pedigree[which(occurrences==pop[p])])
  bottomSample <- unique(occurrences[which(occurrences==pop[p])])
  cat(sprintf("%d: %s Median Yield: %f Sample Size: %d \n", p, bottomPedigree[1], min[p], bottomSample))
}


```
```{R}

max <- head(medYields[order(-medYields)])
min <- tail(medYields[order(-medYields)])
pop <- head(occurrences[order(-occurrences)])
middle <- median(medYields)

cat("Best Pedigrees \n")
for (m in seq(1,5)){
  topPedigree <- pedigree[which(medYields==max[m])]
  topSample <- occurrences[which(medYields==max[m])]
  cat(sprintf("%d: %s Median Yield: %f Sample Size: %d \n", m, topPedigree[1], max[m], topSample))
}

cat("\nMost Popular Pedigree \n")
bottomPedigree <- unique(pedigree[which(occurrences==pop[1])])
bottomSample <- pop[1]
med <- medYields[which(occurrences==pop[1])]
orderedYields <- medYields[order(-medYields)]
location <- which(orderedYields==med[1])
cat(sprintf("%d: %s Median Yield: %f Sample Size: %d \n", location[1], bottomPedigree[1], med[1], bottomSample[1]))

cat("\nMedian Pedigree \n")
topPedigree <- pedigree[which(medYields==middle[1])]
topSample <- occurrences[which(medYields==middle[1])]
location <- which(orderedYields==middle[1])
cat(sprintf("%d: %s Median Yield: %f Sample Size: %d \n", location[1], topPedigree[1], middle[1], topSample))


cat("\nWorst Pedigrees \n")
for (n in seq(1,5)){
  bottomPedigree <- pedigree[which(medYields == min[n])]
  bottomSample <- occurrences[which(medYields==min[n])]
  cat(sprintf("%d: %s Median Yield: %f Sample Size: %d \n", 877+n, bottomPedigree[1], min[n], bottomSample))
}


```


```{R}
par(mfrow=c(1,3))

dkc <- subset(hybridData, hybridData$Pedigree == "DKC63-84")
hoge <- subset(hybridData, hybridData$Pedigree == "HOEGEMEYER HYBRID")
mbx <- subset(hybridData, hybridData$Pedigree == "MBS2747_MBS9508")


barplot(dkc$Grain.yield..bu.A., main="Grain Yields, DKC63-84", ylim=c(0,315), col=rainbow(20))
barplot(hoge$Grain.yield..bu.A., main="Grain Yields, Hoegemeyer Hybrid", ylim=c(0,315), col=rainbow(20))
barplot(mbx$Grain.yield..bu.A., main="Grain Yields, MBS2747_MBS9508", ylim=c(0,315), col=rainbow(30))


hist(dkc$Grain.yield..bu.A., col=rainbow(10))
hist(hoge$Grain.yield..bu.A., col=rainbow(10))
hist(mbx$Grain.yield..bu.A., col="darkslategray3", breaks=25)
```


```{R}

topPedigrees <- c()
#par(mfrow=c(11,3))
for (i in seq(1:881)){
  if (occurrences[i] >= 40){
    popularPedigree <- (pedigree[i][1])
    topPedigrees <- c(topPedigrees, popularPedigree[1])
   # topPedigrees[m,1] <- popularPedigree
    avgYield <- meanYields[i][1]
  #  topPedigrees[m,2] <- avgYield
    medianYield <- medYields[i][1]
   # topPedigrees[m,3] <- medianYield
  #  m <- m+1
    #subsetYield <- subset(hybridData, hybridData$Pedigree == popularPedigree)
   # hist(subsetYield$Grain.yield..bu.A., main=popularPedigree, xlab="Crop Yield")
  }
}

print(topPedigrees)

```


```{R}
rootlodging <- hybridData$Root.lodging..plants
stalklodging <- hybridData$Stalk.lodging..plants

maxroot <- max(rootlodging, na.rm=TRUE)
maxstalk <- max(stalklodging, na.rm=TRUE)
worstRootPedigree <- pedigree[which(rootlodging==maxroot)]
worstStalkPedigree <- pedigree[which(stalklodging==maxstalk)]


minroot <- min(rootlodging, na.rm=TRUE)
minstalk <- min(stalklodging, na.rm=TRUE)
bestRootPedigree <- pedigree[which(rootlodging == minroot)]
bestStalkPedigree <- pedigree[which(stalklodging == minstalk)]

sprintf("Worst Root Lodging Pedigree: %s Root Lodging: %f", worstRootPedigree[1], maxroot[1])
sprintf("Worst Stalk Lodging Pedigree: %s Root Lodging: %f", worstStalkPedigree[1], maxstalk[1])



```


```{R}

dkcindices <- grep("DKC", hybridData$Pedigree)
dkcbreed <- c()

for (t in seq(1, length(dkcindices))){
  
  index <- dkcindices[t]
  dkcbreed <- c(dkcbreed, hybridData$Grain.yield..bu.A.[index])

}

max <- head(medYields[order(-medYields)])
topbreed <- c()
for (m in seq(1,5)){
  topPedigree <- pedigree[which(medYields==max[m])]
  topindices <- grep(topPedigree, hybridData$Pedigree)

  for (t in seq(1, length(topindices))){
    
    index <- topindices[t]
    topbreed <- c(topbreed, hybridData$Grain.yield..bu.A.[index])
  
  }
}

par(mfrow=c(1,2))
hist(mbx$Grain.yield..bu.A., col="turquoise", breaks=25, main="Most Popular Pedigree", xlab="Grain Yield", xlim=c(100,325))
hist(topbreed, breaks=15, xlab="Grain Yield", main="Best Yielding Pedigrees", xlim=c(100,325), col="red2")

```

```{R}
hybridRaw = read.csv('Data/a._2014_hybrid_phenotypic_data/g2f_2014_hybrid_raw.csv')
hybridRaw = subset(hybridRaw, hybridRaw$Plot.Discarded != "Yes" & hybridRaw$Filler != "Yes" & hybridRaw$Grain.yield..bu.A. > 0)
hybridRaw = hybridRaw[!is.na(hybridRaw$Grain.yield..bu.A.),]

grainYield = hybridRaw[, 30]
datePlanted = as.Date(hybridRaw[, 16], "%m/%d/%Y")

meanYieldsByDate = c()
medianYieldsByDate= c()

dates = sort(unique(datePlanted))
print(dates)

for(i in 1:length(dates)) {
indices = which(datePlanted == dates[i])
meanYieldsByDate = c(meanYieldsByDate, mean(grainYield[indices], na.rm = TRUE))
medianYieldsByDate = c(medianYieldsByDate, median(grainYield[indices], na.rm = TRUE))
}

dateLabels = c()
plot(dates, y = medianYieldsByDate, type = "b", xlim = as.Date(c("2014-04-01","2014-06-04")), xlab = "Date Planted", ylab = "Grain Yield", main = "Median Grain Yield by Date Planted", col = "darkviolet", lwd = 3)
text(dates, medianYieldsByDate, labels = c("", "Apr 4", "", "", "", "May 6", "May 7", "May 9", "May 14", "", "", "", "", "May 20", "", "", "", "May 29"), pos = 4, offset = 0.3, font = 2)
```

```{R}
dates = sort(unique(datePlanted))
uniqueLocations <- c()

for(i in 1:length(dates)) {
  
  print(hybridRaw$Date.Planted)
  location <- hybridRaw[which(hybridRaw$Date.Planted == dates[i])]
  uniqueLocations <- c(uniqueLocations, location)

}
print(uniqueLocations)

```